create table if not exists TABLE USERS(ID INTEGER NOT NULL PRIMARY KEY,EMAIL VARCHAR(255),PASSWORD VARCHAR(255),FNAME VARCHAR(255),LNAME VARCHAR(255));
INSERT INTO USERS VALUES(1,'dima_ir@mail.ru','12345678','Dima','Barankin') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO USERS VALUES(2,'test@mail.ru','test','Tester','Testerov') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO USERS VALUES(3,'elkrumina@gmail.com','12345678','Miloe','Sonyshka') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO USERS VALUES(4,'other@mail.ru','12345678','Igorj','Petrushkin') ON DUPLICATE KEY UPDATE id=id;